### ISSUE TITLE
Unordered list is numbered if is nested inside ordered one

### ISSUE THREAD

**Issue by NateWr** [pkp/classic#4] opened 2018-09-14 10:21 UTC
Moved from https://github.com/Vitaliy-1/classic/issues/54

Original message:

> Can be corrected with something like:
> `ul > li:before { content: unset }`

**Comment by sssoz** [comment] 2019-08-21 14:12
@NateWr do we have an example of this happening, and on which template? The original issue no longer exists.

**Comment by NateWr** [comment] 2019-08-21 14:14
No, I don't think I filed the issue. Just moved it over when I migrated the repo. :man_shrugging:

**Comment by sssoz** [comment] 2019-08-21 14:22
It doesn’t seem to be the case anymore in this list that contains sub-items on a custom page: 

<img width="266" alt="Screen Shot 2019-08-21 at 15 22 16" src="https://user-images.githubusercontent.com/6668406/63440311-84113680-c427-11e9-8127-1e6d0fdd7be7.png">

Closing - unable to reproduce

**Closed by sssoz** 2019-08-21 14:22 UTC
